# Generated by Django 4.1.2 on 2022-11-01 14:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetimne_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('discount', models.IntegerField(default=None)),
                ('total', models.FloatField()),
                ('tax', models.FloatField()),
                ('referral_code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Paid'), (3, 'Canceled')])),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetimne_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('template_type', models.IntegerField(choices=[(0, 'Confirmation Email'), (1, 'Reminder Email 1'), (2, 'Reminder Email 2'), (3, 'Reminder Email 3'), (4, 'Rescheduled Email'), (5, 'Canceled Email'), (6, 'New Client to Calendar User'), (7, 'Rescheduled to Calendar User'), (8, 'Canceled to Calendar User')], default=None, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailTemplatesManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_template_to_start_at', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cancelation_policy', models.TextField(blank=True, null=True)),
                ('country', models.CharField(default='', max_length=120)),
                ('data_policy', models.TextField(blank=True, null=True)),
                ('description', models.CharField(default='', max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('invitation_link', models.CharField(default=None, max_length=256, null=True, unique=True)),
                ('link_dashboard', models.CharField(blank=True, max_length=120, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('notification_email', models.EmailField(default='default@email.com', max_length=254)),
                ('notification_email_password', models.BinaryField(default=b'1234')),
                ('phone', models.CharField(max_length=120)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('website', models.CharField(blank=True, max_length=120, null=True)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_first_name', models.CharField(max_length=120)),
                ('owner_last_name', models.CharField(max_length=120)),
                ('owner_phone', models.CharField(max_length=120)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationCampaings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('token', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('budget', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='None/promotions/photos/')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetimne_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField()),
                ('birth_date', models.DateField()),
                ('comments', models.TextField()),
                ('emergency_contact', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('identification', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('phone2', models.CharField(max_length=255)),
                ('known_conditions', models.TextField()),
                ('rating', models.IntegerField()),
                ('referral_link', models.CharField(max_length=255)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetimne_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('accepts_children', models.BooleanField(default=True)),
                ('accepts_pets', models.BooleanField(default=True)),
                ('additional_info', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('schedule', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetimne_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='None/products/photos/')),
                ('is_available', models.BooleanField(default=True)),
                ('amount', models.IntegerField()),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetimne_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_formation', models.TextField(default='')),
                ('about_me', models.TextField(default='')),
                ('certificates', models.FileField(blank=True, null=True, upload_to='None/professionals/certificates/')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('experience', models.TextField(default='')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(default='', max_length=120)),
                ('photos', models.FileField(blank=True, null=True, upload_to='None/professionals/photos/')),
                ('profile_picture', models.CharField(default='', max_length=120)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetimne_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('discount', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='None/promotions/photos/')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetimne_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_interval', models.FloatField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodAcceptedByOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetimne_updated', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetimne_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.IntegerField(choices=[(1, 'Client'), (2, 'Professional')])),
                ('Professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional', to='organization_info.organizationprofessional')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='organization_info.organizationclient')),
            ],
        ),
    ]
