# Generated by Django 4.1.2 on 2022-11-01 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='deleted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organizationservice'),
        ),
        migrations.AddField(
            model_name='professionalspeciality',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_speciality_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professionalspeciality',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organization'),
        ),
        migrations.AddField(
            model_name='professionalspeciality',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_speciality_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethodacceptedbyorg',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods_accepted', to='organization_info.organization'),
        ),
        migrations.AddField(
            model_name='organizationservice',
            name='deleted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationservice',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization_info.organization'),
        ),
        migrations.AddField(
            model_name='organizationservice',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationpromotion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_promotion_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationpromotion',
            name='deleted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_promotion_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationpromotion',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organization'),
        ),
        migrations.AddField(
            model_name='organizationpromotion',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organizationservice'),
        ),
        migrations.AddField(
            model_name='organizationpromotion',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_promotion_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationprofessional',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationprofessional',
            name='deleted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationprofessional',
            name='kumbio_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_professional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationprofessional',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_professionals', to='organization_info.organization'),
        ),
        migrations.AddField(
            model_name='organizationprofessional',
            name='specialities',
            field=models.ManyToManyField(to='organization_info.professionalspeciality'),
        ),
        migrations.AddField(
            model_name='organizationprofessional',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationproduct',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_product_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationproduct',
            name='deleted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_product_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationproduct',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organization'),
        ),
        migrations.AddField(
            model_name='organizationproduct',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_product_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationoffice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationoffice',
            name='deleted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationoffice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organization'),
        ),
        migrations.AddField(
            model_name='organizationoffice',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, to='organization_info.paymentmethodacceptedbyorg'),
        ),
        migrations.AddField(
            model_name='organizationoffice',
            name='services',
            field=models.ManyToManyField(to='organization_info.organizationservice'),
        ),
        migrations.AddField(
            model_name='organizationoffice',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationclient',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_client_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationclient',
            name='deleted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_client_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationclient',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organization'),
        ),
        migrations.AddField(
            model_name='organizationclient',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_client_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationcampaings',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_campaing_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationcampaings',
            name='deleted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_campaing_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationcampaings',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organization'),
        ),
        migrations.AddField(
            model_name='organizationcampaings',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_campaing_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization_info.sector'),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='deleted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization_info.organization'),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organizationclient'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organizationoffice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organization'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organizationprofessional'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization_info.organizationpromotion'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organizationservice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='deleted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organization'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organizationprofessional'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organizationservice'),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
