# Generated by Django 4.1.2 on 2022-11-01 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_info', '0003_organization_default_template_starts_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationoffice',
            name='local_timezone',
            field=models.CharField(default='America/Bogota', max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='CalendarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_notification_to', models.EmailField(default=None, max_length=254, null=True)),
                ('send_first_notification', models.IntegerField(blank=True, default=24, null=True)),
                ('send_second_notification', models.IntegerField(blank=True, default=None, null=True)),
                ('send_third_notification', models.IntegerField(blank=True, default=None, null=True)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetimne_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_settings_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_settings_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization_info.organization')),
                ('template_to_send_as_canceled', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancel_template', to='organization_info.mailtemplate')),
                ('template_to_send_as_canceled_to_calendar_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canceled_to_calendar_user_template', to='organization_info.mailtemplate')),
                ('template_to_send_as_confirmation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_template', to='organization_info.mailtemplate')),
                ('template_to_send_as_new_client_to_calendar_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_client_to_organization_template', to='organization_info.mailtemplate')),
                ('template_to_send_as_reminder_1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_reminder_template', to='organization_info.mailtemplate')),
                ('template_to_send_as_reminder_2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_reminder_template', to='organization_info.mailtemplate')),
                ('template_to_send_as_reminder_3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_reminder_template', to='organization_info.mailtemplate')),
                ('template_to_send_as_rescheduled', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rescheduled_template', to='organization_info.mailtemplate')),
                ('template_to_send_as_rescheduled_to_calendar_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rescheduled_to_calendar_user_template', to='organization_info.mailtemplate')),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_settings_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
