# Generated by Django 4.1.2 on 2022-11-02 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_info', '0004_organizationoffice_local_timezone_calendarsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationprofessional',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organizationprofessional',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='organizationprofessional',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='organizationprofessional',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='organizationprofessional',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='organizationprofessional',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='None/professionals/profile_photos/'),
        ),
        migrations.AlterField(
            model_name='organizationprofessional',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationprofessional',
            name='academic_formation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationprofessional',
            name='deleted_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationprofessional',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationprofessional',
            name='specialities',
            field=models.ManyToManyField(blank=True, to='organization_info.professionalspeciality'),
        ),
        migrations.AlterField(
            model_name='organizationprofessional',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
