# Generated by Django 4.1.2 on 2022-11-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0006_organizationplace_remove_invoice_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationplace',
            name='services',
            field=models.ManyToManyField(blank=True, to='organization_info.organizationservice'),
        ),
    ]
