# Generated by Django 4.1.2 on 2022-11-02 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_info', '0007_alter_organizationplace_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationplace',
            old_name='payment_methods',
            new_name='payment_methods_accepted',
        ),
        migrations.AlterField(
            model_name='organizationplace',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizaion_place_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationplace',
            name='deleted_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizaion_place_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationplace',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizaion_place_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
