# Generated by Django 4.1.2 on 2022-11-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0009_remove_mailtemplate_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationplace',
            name='custom_price',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='organizationprofessional',
            name='custom_price',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='organizationservice',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='notification_email',
            field=models.EmailField(default='Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='organization',
            name='notification_email_password',
            field=models.BinaryField(default=b'password'),
        ),
    ]
