# Generated by Django 4.1.2 on 2022-11-14 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_info', '0010_organizationplace_custom_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='notification_email',
            field=models.EmailField(default='default@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='organization',
            name='notification_email_password',
            field=models.BinaryField(default=b'1234'),
        ),
        migrations.AlterField(
            model_name='organizationservice',
            name='deleted_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationservice',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organizationservice',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
