# Generated by Django 4.1.2 on 2022-11-16 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_info', '0011_alter_organization_notification_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCampaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('token', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('budget', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='None/promotions/photos/')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_campaign_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_campaign_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_specialty_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='professionalspeciality',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='professionalspeciality',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='professionalspeciality',
            name='updated_by',
        ),
        migrations.RenameField(
            model_name='calendarsettings',
            old_name='datetimne_updated',
            new_name='datetime_updated',
        ),
        migrations.RenameField(
            model_name='frequentlyaskedquestion',
            old_name='datetimne_updated',
            new_name='datetime_updated',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='datetimne_updated',
            new_name='datetime_updated',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='cancelation_policy',
            new_name='cancellation_policy',
        ),
        migrations.RenameField(
            model_name='organizationclient',
            old_name='datetimne_updated',
            new_name='datetime_updated',
        ),
        migrations.RenameField(
            model_name='organizationplace',
            old_name='datetimne_updated',
            new_name='datetime_updated',
        ),
        migrations.RenameField(
            model_name='organizationproduct',
            old_name='datetimne_updated',
            new_name='datetime_updated',
        ),
        migrations.RenameField(
            model_name='organizationprofessional',
            old_name='datetimne_updated',
            new_name='datetime_updated',
        ),
        migrations.RenameField(
            model_name='organizationpromotion',
            old_name='datetimne_updated',
            new_name='datetime_updated',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='datetimne_updated',
            new_name='datetime_updated',
        ),
        migrations.RemoveField(
            model_name='organizationprofessional',
            name='specialities',
        ),
        migrations.AlterField(
            model_name='organizationplace',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_place_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationplace',
            name='deleted_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_place_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationplace',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_place_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OrganizationCampaings',
        ),
        migrations.DeleteModel(
            name='ProfessionalSpeciality',
        ),
        migrations.AddField(
            model_name='professionalspecialty',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organization'),
        ),
        migrations.AddField(
            model_name='professionalspecialty',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_specialty_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationcampaigns',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organization'),
        ),
        migrations.AddField(
            model_name='organizationcampaigns',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_campaign_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationprofessional',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='organization_info.professionalspecialty'),
        ),
    ]
