# Generated by Django 4.1.2 on 2022-11-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0012_organizationcampaigns_professionalspecialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='template_to_send_as_canceled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='template_to_send_as_canceled_to_calendar_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='template_to_send_as_confirmation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='template_to_send_as_new_client_to_calendar_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='template_to_send_as_reminder_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='template_to_send_as_reminder_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='template_to_send_as_rescheduled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='template_to_send_as_rescheduled_to_calendar_user',
            field=models.IntegerField(default=0),
        ),
    ]
