# Generated by Django 4.1.2 on 2022-11-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0014_alter_organization_notification_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='language',
            field=models.CharField(default='', max_length=120),
        ),
    ]
