# Generated by Django 4.0.4 on 2022-11-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0015_organization_currency_organization_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationplace',
            name='admin_email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationplace',
            name='after_hours_phone',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationplace',
            name='google_maps_link',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationplace',
            name='important_information',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='organizationplace',
            name='main_office_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='notification_email',
            field=models.EmailField(default='AADAS', max_length=254),
        ),
        migrations.AlterField(
            model_name='organization',
            name='notification_email_password',
            field=models.BinaryField(default=b'as'),
        ),
    ]
