# Generated by Django 4.0.4 on 2022-11-25 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_info', '0016_organizationplace_admin_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationclient',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='organizationclient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organizationclient',
            name='known_conditions',
        ),
        migrations.RemoveField(
            model_name='organizationclient',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='organizationclient',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='organizationplace',
            name='closes_at',
        ),
        migrations.RemoveField(
            model_name='organizationplace',
            name='opens_at',
        ),
        migrations.AddField(
            model_name='organizationclient',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='organizationclient',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='OrganizationClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('fields', models.JSONField()),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_type_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_client_types', to='organization_info.organization')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationClientDependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True)),
                ('same_as_client', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_dependent', to='organization_info.organizationclient')),
            ],
        ),
        migrations.CreateModel(
            name='DayAvailableForPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('exclude', models.JSONField(blank=True, default=[[0, 7], [18, 23]], null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organizationplace')),
            ],
        ),
        migrations.AddField(
            model_name='organizationclient',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization_info.organizationclienttype'),
        ),
    ]
