# Generated by Django 4.1.2 on 2022-11-27 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0017_remove_organizationclient_allergies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KumbioToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.IntegerField(choices=[(1, 'Calendar'), (2, 'Orders'), (3, 'Communications')])),
                ('token', models.CharField(editable=False, max_length=120, unique=True)),
                ('is_tester', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='frequentlyaskedquestion',
            old_name='datetime_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='frequentlyaskedquestion',
            old_name='datetime_deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='frequentlyaskedquestion',
            old_name='datetime_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='datetime_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='datetime_deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='datetime_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='organizationcampaigns',
            old_name='datetime_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='organizationcampaigns',
            old_name='datetime_deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='organizationcampaigns',
            old_name='datetime_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='organizationclient',
            old_name='datetime_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='organizationclient',
            old_name='datetime_deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='organizationclient',
            old_name='datetime_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='organizationclienttype',
            old_name='datetime_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='organizationclienttype',
            old_name='datetime_deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='organizationclienttype',
            old_name='datetime_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='organizationplace',
            old_name='datetime_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='organizationplace',
            old_name='datetime_deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='organizationplace',
            old_name='datetime_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='organizationproduct',
            old_name='datetime_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='organizationproduct',
            old_name='datetime_deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='organizationproduct',
            old_name='datetime_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='organizationprofessional',
            old_name='datetime_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='organizationprofessional',
            old_name='datetime_deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='organizationprofessional',
            old_name='datetime_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='organizationpromotion',
            old_name='datetime_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='organizationpromotion',
            old_name='datetime_deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='organizationpromotion',
            old_name='datetime_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='professionalspecialty',
            old_name='datetime_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='professionalspecialty',
            old_name='datetime_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='datetime_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='datetime_deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='datetime_updated',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='organization',
            name='notification_email',
            field=models.EmailField(default='Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='organization',
            name='notification_email_password',
            field=models.BinaryField(default=b'password'),
        ),
    ]
