# Generated by Django 4.1.2 on 2022-11-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0021_delete_kumbiotoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationclient',
            name='created_by',
        ),
    ]
