# Generated by Django 4.1.2 on 2022-11-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0022_remove_organizationclient_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationclient',
            name='created_by',
            field=models.IntegerField(choices=[(1, 'Calendar'), (2, 'Selene'), (3, 'Kumbio'), (4, 'Orders')], default=1),
        ),
    ]
