# Generated by Django 4.1.2 on 2022-11-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0023_organizationclient_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationclient',
            name='created_by',
            field=models.IntegerField(choices=[(1, 'Calendar'), (2, 'Orders'), (3, 'Kumbio'), (4, 'Communications')], default=1),
        ),
    ]
