# Generated by Django 4.1.2 on 2022-11-28 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0025_organizationclient_extra_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationclienttype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_client_type', to='organization_info.organization'),
        ),
    ]
