# Generated by Django 4.1.2 on 2022-11-30 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0027_alter_organizationclienttype_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayAvailableForProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('services_time', models.JSONField(default=list)),
                ('note', models.TextField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_info.organizationprofessional')),
            ],
        ),
    ]
