# Generated by Django 4.1.2 on 2022-11-30 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0028_dayavailableforprofessional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationclient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organizationclient',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
