# Generated by Django 4.1.2 on 2022-12-01 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0029_alter_organizationclient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayavailableforplace',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dayavailableforplace',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
