# Generated by Django 4.1.2 on 2022-12-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0031_rename_created_by_organizationclient_created_by_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='currency',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
