# Generated by Django 4.1.2 on 2022-12-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0032_alter_organization_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationclient',
            name='birth_date',
        ),
    ]
