# Generated by Django 4.1.2 on 2022-12-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0034_organizationservice_buffer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethodacceptedbyorg',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_methods_accepted',
            field=models.ManyToManyField(blank=True, related_name='payment_methods_accepted_by_org', to='organization_info.paymentmethodacceptedbyorg'),
        ),
        migrations.AddField(
            model_name='paymentmethodacceptedbyorg',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
