# Generated by Django 4.1.2 on 2022-12-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0035_remove_paymentmethodacceptedbyorg_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofessional',
            name='services',
            field=models.ManyToManyField(to='organization_info.organizationservice'),
        ),
    ]
