# Generated by Django 4.1.2 on 2022-12-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0036_organizationprofessional_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='organization_logos'),
        ),
    ]
