# Generated by Django 4.0.4 on 2022-12-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0037_alter_organization_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayavailableforprofessional',
            old_name='day',
            new_name='professional',
        ),
        migrations.RemoveField(
            model_name='dayavailableforprofessional',
            name='services_time',
        ),
        migrations.AddField(
            model_name='dayavailableforprofessional',
            name='exclude',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofessional',
            name='certification_number',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofessional',
            name='charge',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofessional',
            name='identification_number',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='notification_email',
            field=models.EmailField(default='AADAS', max_length=254),
        ),
        migrations.AlterField(
            model_name='organization',
            name='notification_email_password',
            field=models.BinaryField(default=b'as'),
        ),
    ]
