# Generated by Django 4.0.4 on 2023-01-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0040_organizationclient_send_marketing_by_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='notification_email',
            field=models.EmailField(default='AADAS', max_length=254),
        ),
        migrations.AlterField(
            model_name='organization',
            name='notification_email_password',
            field=models.BinaryField(default=b'as'),
        ),
    ]
