# Generated by Django 4.1.2 on 2023-01-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0042_organizationplace_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationservice',
            name='buffer',
            field=models.FloatField(default=0),
        ),
    ]
