# Generated by Django 4.1.2 on 2023-01-18 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0043_alter_organizationservice_buffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationservice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
