# Generated by Django 4.1.2 on 2023-01-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0046_alter_organizationservice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationclientdependent',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organizationclientdependent',
            name='phone_2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
