# Generated by Django 4.1.2 on 2023-01-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0047_alter_organizationclientdependent_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayavailableforprofessional',
            name='services',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
