# Generated by Django 4.1.2 on 2023-01-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0048_dayavailableforprofessional_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofessional',
            name='calendar_link',
            field=models.CharField(default='d76-Mz-HcbSlFpXPJ1NN_Dzo3k6v', max_length=255),
        ),
        migrations.DeleteModel(
            name='OrganizationProduct',
        ),
    ]
