# Generated by Django 4.1.2 on 2023-01-30 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0049_organizationprofessional_calendar_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('phone_2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('identification', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('emergency_contact', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('same_as_client', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='organizationclient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='organizationclient',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='organizationclient',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='organizationclient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='organizationclient',
            name='identification',
        ),
        migrations.RemoveField(
            model_name='organizationclient',
            name='last_name',
        ),
        migrations.DeleteModel(
            name='OrganizationClientDependent',
        ),
        migrations.AddField(
            model_name='organizationclient',
            name='client_dependent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_dependent', to='organization_info.clientparent'),
        ),
    ]
