# Generated by Django 4.1.2 on 2023-01-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0049_alter_organization_notification_email_and_more'),
        ('organization_info', '0049_organizationprofessional_calendar_link_and_more'),
    ]

    operations = [
    ]
