# Generated by Django 4.1.2 on 2023-01-31 20:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0050_clientparent_remove_organizationclient_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationservice',
            old_name='only_booking',
            new_name='online_booking',
        ),
        migrations.RemoveField(
            model_name='organizationclient',
            name='organization',
        ),
        migrations.AddField(
            model_name='clientparent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clientparent',
            name='organization',
            field=models.ForeignKey(default='ZxBXSCAsWATJJy8-pYHn1O7q0KYA', on_delete=django.db.models.deletion.CASCADE, to='organization_info.organization'),
        ),
        migrations.AddField(
            model_name='clientparent',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='organizationclient',
            name='first_name',
            field=models.CharField(default='first_name', max_length=100),
        ),
        migrations.AddField(
            model_name='organizationclient',
            name='last_name',
            field=models.CharField(default='last_name', max_length=100),
        ),
        migrations.AddField(
            model_name='organizationclienttype',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='organization_info.sector'),
        ),
        migrations.AlterField(
            model_name='clientparent',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
