# Generated by Django 4.1.2 on 2023-01-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0051_rename_only_booking_organizationservice_online_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientparent',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
