# Generated by Django 4.1.2 on 2023-01-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0052_alter_clientparent_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientparent',
            name='organization',
        ),
        migrations.AlterField(
            model_name='clientparent',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
