# Generated by Django 4.1.2 on 2023-02-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0053_remove_clientparent_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationclienttype',
            name='sector',
        ),
    ]
