# Generated by Django 4.1.2 on 2023-02-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0055_organizationclienttype_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationclient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='organizationclient',
            name='last_name',
        ),
    ]
