# Generated by Django 4.1.2 on 2023-02-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0056_remove_organizationclient_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationclient',
            name='first_name',
            field=models.CharField(default='first_name', max_length=100),
        ),
        migrations.AddField(
            model_name='organizationclient',
            name='last_name',
            field=models.CharField(default='last_name', max_length=100),
        ),
    ]
