# Generated by Django 4.1.2 on 2023-02-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0057_organizationclient_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
