# Generated by Django 4.1.2 on 2023-02-01 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0059_alter_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientparent',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization_info.organization'),
        ),
    ]
