# Generated by Django 4.1.2 on 2023-02-08 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0060_clientparent_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationclient',
            name='client_dependent',
        ),
        migrations.AddField(
            model_name='clientparent',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationclient',
            name='client_parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_child', to='organization_info.clientparent'),
        ),
    ]
