# Generated by Django 4.1.2 on 2023-02-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0050_merge_20230127_1409'),
        ('organization_info', '0061_remove_organizationclient_client_dependent_and_more'),
    ]

    operations = [
    ]
