# Generated by Django 4.1.2 on 2023-02-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0063_organization_default_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='default_timezone',
            field=models.CharField(blank=True, default='America/Caracas', max_length=120, null=True),
        ),
    ]
