# Generated by Django 4.1.2 on 2023-02-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0062_merge_20230208_1828'),
        ('organization_info', '0063_organization_default_timezone'),
    ]

    operations = [
    ]
