# Generated by Django 4.1.2 on 2023-02-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0064_alter_organization_default_timezone'),
        ('organization_info', '0064_merge_20230210_1546'),
    ]

    operations = [
    ]
