# Generated by Django 4.1.2 on 2023-02-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0064_alter_organization_default_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_client_type',
            field=models.IntegerField(default=5),
        ),
    ]
