# Generated by Django 4.1.2 on 2023-02-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0065_organization_default_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='about_us_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='about_us'),
        ),
    ]
