# Generated by Django 4.1.2 on 2023-02-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0066_organization_about_us_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='spanish_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
