# Generated by Django 4.1.2 on 2023-02-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0065_merge_20230210_1629'),
        ('organization_info', '0066_organization_about_us_image'),
    ]

    operations = [
    ]
