# Generated by Django 4.1.2 on 2023-03-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0067_sector_spanish_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='number_of_active_appointments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='number_of_appointments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='number_of_clients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='number_of_professionals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='number_of_services',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizationservice',
            name='number_of_active_appointments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizationservice',
            name='number_of_appointments',
            field=models.IntegerField(default=0),
        ),
    ]
