# Generated by Django 4.1.2 on 2023-02-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0067_merge_20230217_1939'),
        ('organization_info', '0067_sector_spanish_name'),
    ]

    operations = [
    ]
