# Generated by Django 4.1.2 on 2023-03-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0068_organization_number_of_active_appointments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='banner_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='banner'),
        ),
        migrations.AddField(
            model_name='organization',
            name='banner_text',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
