# Generated by Django 4.1.2 on 2023-03-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0068_merge_20230223_1442'),
        ('organization_info', '0068_organization_number_of_active_appointments_and_more'),
    ]

    operations = [
    ]
