# Generated by Django 4.1.2 on 2023-03-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0069_merge_20230302_1957'),
        ('organization_info', '0069_organization_banner_image_organization_banner_text'),
    ]

    operations = [
    ]
