# Generated by Django 4.0.4 on 2023-03-07 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0069_organization_banner_image_organization_banner_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='clients/documents/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_document', to='organization_info.organizationclient')),
            ],
        ),
    ]
