# Generated by Django 4.1.2 on 2023-03-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0070_organizationclientdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationclienttype',
            name='spanish_fields',
            field=models.JSONField(default=list),
        ),
    ]
