# Generated by Django 4.1.2 on 2023-03-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0070_merge_20230306_1954'),
        ('organization_info', '0071_organizationclienttype_spanish_fields'),
    ]

    operations = [
    ]
