# Generated by Django 4.1.2 on 2023-03-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_info', '0072_merge_20230308_1433'),
        ('organization_info', '0072_organization_slogan'),
    ]

    operations = [
    ]
