# Generated by Django 4.1.2 on 2022-12-02 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_info', '0035_remove_paymentmethodacceptedbyorg_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'Paid'), (2, 'Pending'), (3, 'Cancelled')])),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_after_taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_note', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_invoice_client', to='organization_info.organizationclient')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_invoice_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_invoice_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_invoice_organization', to='organization_info.organization')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_invoice_payment_method', to='organization_info.paymentmethodacceptedbyorg')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_invoice_place', to='organization_info.organizationplace')),
                ('products', models.ManyToManyField(blank=True, related_name='appointment_invoice_products', to='organization_info.organizationservice')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_invoice_professional', to='organization_info.organizationprofessional')),
                ('promotion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_invoice_promotion', to='organization_info.organizationpromotion')),
                ('services', models.ManyToManyField(related_name='appointment_invoice_services', to='organization_info.organizationservice')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_invoice_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment Invoice',
                'verbose_name_plural': 'Appointment Invoices',
            },
        ),
    ]
