# Generated by Django 4.1.2 on 2022-12-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentinvoice',
            old_name='total_after_taxes',
            new_name='total',
        ),
    ]
