# Generated by Django 4.1.2 on 2022-12-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_total_after_taxes_appointmentinvoice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentinvoice',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointmentinvoice',
            name='status',
            field=models.IntegerField(choices=[(1, 'Paid'), (2, 'Pending'), (3, 'Cancelled')], default=2),
        ),
    ]
