# Generated by Django 4.1.2 on 2022-11-27 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KumbioToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.IntegerField(choices=[(1, 'Calendar'), (2, 'Orders'), (3, 'Communications')])),
                ('token', models.CharField(editable=False, max_length=120, unique=True)),
                ('is_tester', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
