# Generated by Django 4.1.2 on 2022-11-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kumbiotoken',
            name='app',
            field=models.IntegerField(choices=[(1, 'Calendar'), (2, 'Orders'), (3, 'Kumbio'), (4, 'Communications')]),
        ),
    ]
