# Generated by Django 4.1.2 on 2023-01-23 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_manager', '0003_kumbiotoken_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDashboardToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=120, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='kumbiotoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
