# Generated by Django 4.1.2 on 2022-11-01 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organization_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KumbioUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KumbioUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('permissions', models.ManyToManyField(blank=True, to='user_info.kumbiouserpermission')),
            ],
        ),
        migrations.CreateModel(
            name='KumbioUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('code_to_verify_email', models.CharField(default=None, max_length=256, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_tester', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(default='', max_length=120)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('default_template_starts_at', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('organization', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_user', to='organization_info.organization')),
                ('role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_info.kumbiouserrole')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
