# Generated by Django 4.1.2 on 2022-11-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kumbiouser',
            name='default_template_starts_at',
        ),
    ]
