# Generated by Django 4.1.2 on 2022-11-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_kumbiouser_calendar_token_kumbiouser_selene_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='kumbiouser',
            name='extra_permissions',
            field=models.ManyToManyField(blank=True, to='user_info.kumbiouserpermission'),
        ),
    ]
