# Generated by Django 4.1.2 on 2022-12-01 18:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0006_kumbiouser_available_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_confirmation', models.BooleanField(default=True)),
                ('appointment_reschedule', models.BooleanField(default=True)),
                ('appointment_cancellation', models.BooleanField(default=True)),
                ('day_briefing', models.BooleanField(default=True)),
                ('time_to_receive_briefing', models.TimeField(default=datetime.time(8, 0))),
                ('email', models.BooleanField(default=True)),
                ('sms', models.BooleanField(default=False)),
                ('whatsapp', models.BooleanField(default=False)),
                ('low_inventory', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
