# Generated by Django 4.1.2 on 2023-02-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0008_kumbiouser_code_to_recover_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kumbiouser',
            name='calendar_link',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
